name: animecam
channels:
  - conda-forge
dependencies:
  - python=3.8
  - tensorflow=2.12       # 2.x 系
  - opencv                 # conda-forge 上の OpenCV
  - h5py                   # conda-forge 上の h5py
  - pip
